### ISSUE TITLE
[User Story] Edit handles

### ISSUE THREAD

**Issue by florian-papsdorf** [hpi-swt2/contacts-portal#113] opened 2021-01-10 17:37 UTC
# Description
No other user could edit my personal social media handles.

# Dependencies
- [ ] I can save and edit handles in my profile. (#69)

# Conditions of satisfaction
- [ ] I can edit my handles.
- [ ] Another person cannot edit my personal handles.

**Comment by LinqLover** [comment] 2021-01-11 09:15
Duplicate of #112 :)

**Closed as completed by LinqLover** 2021-01-11 09:15 UTC
Labels: prio: medium, team-ε, user-story
